spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  cloud:
    config:
      name: config-client1
      uri: http://localhost:8888
      profile: prod
      label: master

server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
    hystrix:
      enabled: true